/**
 * Historical display names for faction rulers. Picked at random when a battle is prepared
 * (each new play / start from setup); save restores keep the serialized `name` field.
 */
export const RULER_HISTORICAL_NAMES: Record<string, readonly string[]> = {
  "Roman King": [
    "Augustus",
    "Julius Caesar",
    "Trajan",
    "Marcus Aurelius",
    "Constantine",
    "Scipio Africanus",
    "Pompey",
    "Hadrian",
    "Diocletian",
    "Aurelian",
    "Fabius Maximus",
    "Marius",
    "Sulla",
    "Tiberius",
    "Claudius",
    "Vespasian",
    "Antoninus Pius",
    "Belisarius"
  ],
  "Barbarian Chief": [
    "Arminius",
    "Alaric",
    "Attila",
    "Odoacer",
    "Theodoric",
    "Viriathus",
    "Brennus",
    "Gaiseric",
    "Ricimer",
    "Ostrogotha",
    "Fritigern",
    "Radagaisus",
    "Totila",
    "Ermanaric",
    "Valamir"
  ],
  "Macedonian King": [
    "Alexander",
    "Philip II",
    "Cassander",
    "Antigonus",
    "Demetrius Poliorcetes",
    "Perseus",
    "Lysimachus",
    "Seleucus",
    "Antipater",
    "Archelaus",
    "Amyntas IV",
    "Ptolemy Ceraunus",
    "Pyrrhus",
    "Antigonus Gonatas",
    "Philip V"
  ],
  "Gallic King": [
    "Vercingetorix",
    "Ambiorix",
    "Brennus",
    "Diviciacus",
    "Commius",
    "Virdomarus",
    "Dumnorix",
    "Concolitanus",
    "Aneroëstes",
    "Bituitus",
    "Cativolcus",
    "Indutiomarus",
    "Viridomarus",
    "Critognatus",
    "Vercassivellaunus"
  ],
  "Germanic King": [
    "Arminius",
    "Marbod",
    "Chrocus",
    "Theodemar",
    "Alaric",
    "Gundobad",
    "Clovis",
    "Theodoric",
    "Ermanaric",
    "Radagaisus",
    "Ricimer",
    "Genseric",
    "Odoacer",
    "Childeric",
    "Sigebert"
  ],
  "Carthaginian General": [
    "Hannibal",
    "Hasdrubal Barca",
    "Hamilcar Barca",
    "Mago Barca",
    "Maharbal",
    "Hanno the Great",
    "Hasdrubal Gisco",
    "Bomilcar",
    "Xanthippus",
    "Adherbal",
    "Carthalo",
    "Himilco",
    "Hamilcar",
    "Hasdrubal the Fair",
    "Hanno the Navigator"
  ],
  Pharaoh: [
    "Ramses II",
    "Thutmose III",
    "Hatshepsut",
    "Akhenaten",
    "Tutankhamun",
    "Amenhotep III",
    "Khufu",
    "Djoser",
    "Sesostris III",
    "Ptolemy I",
    "Ptolemy II",
    "Cleopatra VII",
    "Psamtik I",
    "Shoshenq I",
    "Seti I"
  ],
  "Thracian King": [
    "Spartacus",
    "Seuthes III",
    "Cersobleptes",
    "Rhometalces I",
    "Sitalces",
    "Lysimachus",
    "Cotys I",
    "Teres I",
    "Seuthes II",
    "Rhoemetalces II",
    "Cotys II",
    "Sadalas",
    "Rhescuporis",
    "Dromichaetes",
    "Cothelas"
  ],
  "Dacian King": [
    "Decebalus",
    "Burebista",
    "Scorilo",
    "Comosicus",
    "Duras",
    "Dromichaetes",
    "Zalmodegikos",
    "Rubobostes",
    "Oroles",
    "Dicomes",
    "Zyraxes",
    "Rholes",
    "Pieporus",
    "Zoltes",
    "Diegis"
  ],
  "Parthian King": [
    "Mithridates II",
    "Phraates IV",
    "Orodes II",
    "Vologases I",
    "Surena",
    "Phraates III",
    "Gotarzes II",
    "Vonones I",
    "Artabanus II",
    "Pacorus I",
    "Sinatruces",
    "Phraates V",
    "Vardanes I",
    "Artabanus III",
    "Mithridates III"
  ],
  "Seleucid King": [
    "Seleucus I",
    "Antiochus III",
    "Antiochus IV Epiphanes",
    "Seleucus II",
    "Antiochus I",
    "Demetrius I",
    "Antiochus VII",
    "Seleucus IV",
    "Antiochus II",
    "Demetrius II",
    "Alexander Balas",
    "Philip I Philadelphus",
    "Antiochus VI",
    "Tryphon",
    "Antiochus XII"
  ],
  Jarl: [
    "Harald Fairhair",
    "Erik the Red",
    "Olaf Tryggvason",
    "Cnut the Great",
    "Harald Hardrada",
    "Leif Erikson",
    "Ragnar Lothbrok",
    "Ivar the Boneless",
    "Björn Ironside",
    "Sigurd Snake-in-the-Eye",
    "Haakon the Good",
    "Olaf Haraldsson",
    "Sweyn Forkbeard",
    "Rollo",
    "Egil Skallagrimsson"
  ]
};

export const pickRandomLeaderDisplayName = (role: string): string | null => {
  const pool = RULER_HISTORICAL_NAMES[role];
  if (!pool?.length) return null;
  const i = Math.floor(Math.random() * pool.length);
  return pool[i] ?? null;
};
