import { generateTroopStats } from "./troopStats";

const createUnit = (
  id: string,
  team: string,
  name: string,
  role: string,
  x: number,
  y: number,
  Icon: string
) => ({
  id,
  team,
  name,
  ...generateTroopStats(role),
  x,
  y,
  role,
  Icon
});

export const levels = {
  Level1: [
    createUnit("roman_king", "Romans", "Roman King", "Roman King", 3, 0, "👑"),
    createUnit("roman_ballista_left", "Romans", "Ballista", "Ballista", 0, 0, "⚔️"),
    createUnit("roman_ballista_right", "Romans", "Ballista", "Ballista", 7, 0, "⚔️"),
    createUnit("roman_praetorian", "Romans", "Praetorian", "Praetorian", 4, 0, "🪖"),
    createUnit("roman_cavalry_left", "Romans", "Cavalry", "Cavalry", 1, 1, "🐎"),
    createUnit("roman_archer_left", "Romans", "Archer", "Archer", 2, 1, "🏹"),
    createUnit("roman_archer_right", "Romans", "Archer", "Archer", 5, 1, "🏹"),
    createUnit("roman_cavalry_right", "Romans", "Cavalry", "Cavalry", 6, 1, "🐎"),
    createUnit("roman_legionary_1", "Romans", "Legionary", "Legionary", 0, 2, "⚔️"),
    createUnit("roman_legionary_2", "Romans", "Legionary", "Legionary", 1, 2, "⚔️"),
    createUnit("roman_legionary_3", "Romans", "Legionary", "Legionary", 2, 2, "⚔️"),
    createUnit("roman_legionary_4", "Romans", "Legionary", "Legionary", 3, 2, "⚔️"),
    createUnit("roman_legionary_5", "Romans", "Legionary", "Legionary", 4, 2, "⚔️"),
    createUnit("roman_legionary_6", "Romans", "Legionary", "Legionary", 5, 2, "⚔️"),
    createUnit("roman_legionary_7", "Romans", "Legionary", "Legionary", 6, 2, "⚔️"),
    createUnit("roman_legionary_8", "Romans", "Legionary", "Legionary", 7, 2, "⚔️"),
    createUnit("barbarian_chief", "Barbarians", "Barbarian Chief", "Barbarian Chief", 4, 7, "👑"),
    createUnit("barbarian_axeman_left", "Barbarians", "Barbarian Axeman", "Barbarian Axeman", 0, 7, "⚔️"),
    createUnit("barbarian_berserker", "Barbarians", "Barbarian Berserker", "Barbarian Berserker", 3, 7, "⚔️"),
    createUnit("barbarian_axeman_right", "Barbarians", "Barbarian Axeman", "Barbarian Axeman", 7, 7, "⚔️"),
    createUnit("barbarian_scout_left", "Barbarians", "Barbarian Scout", "Barbarian Scout", 1, 6, "🐎"),
    createUnit("barbarian_archer_left", "Barbarians", "Barbarian Archer", "Barbarian Archer", 2, 6, "🏹"),
    createUnit("barbarian_archer_right", "Barbarians", "Barbarian Archer", "Barbarian Archer", 5, 6, "🏹"),
    createUnit("barbarian_scout_right", "Barbarians", "Barbarian Scout", "Barbarian Scout", 6, 6, "🐎"),
    createUnit("barbarian_warrior_1", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 0, 5, "🪓"),
    createUnit("barbarian_warrior_2", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 1, 5, "🪓"),
    createUnit("barbarian_warrior_3", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 2, 5, "🪓"),
    createUnit("barbarian_warrior_4", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 3, 5, "🪓"),
    createUnit("barbarian_warrior_5", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 4, 5, "🪓"),
    createUnit("barbarian_warrior_6", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 5, 5, "🪓"),
    createUnit("barbarian_warrior_7", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 6, 5, "🪓"),
    createUnit("barbarian_warrior_8", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 7, 5, "🪓")
  ],
  Level2: [
    createUnit("greek_king", "Greeks", "Macedonian King", "Macedonian King", 3, 0, "👑"),
    createUnit("greek_hoplite_1", "Greeks", "Hoplite", "Hoplite", 2, 1, "⚔️"),
    createUnit("greek_hoplite_2", "Greeks", "Hoplite", "Hoplite", 3, 1, "⚔️"),
    createUnit("greek_hoplite_3", "Greeks", "Hoplite", "Hoplite", 4, 1, "⚔️"),
    createUnit("greek_hoplite_4", "Greeks", "Hoplite", "Hoplite", 3, 2, "⚔️"),
    createUnit("greek_archer_1", "Greeks", "Cretan Archer", "Cretan Archer", 1, 2, "🏹"),
    createUnit("greek_archer_2", "Greeks", "Cretan Archer", "Cretan Archer", 5, 2, "🏹"),
    createUnit("greek_cavalry", "Greeks", "Companion Cavalry", "Companion Cavalry", 6, 1, "🐎"),
    createUnit("celt_king", "Celts", "Celtic King", "Celtic King", 4, 7, "👑"),
    createUnit("celt_warrior_1", "Celts", "Celtic Warrior", "Celtic Warrior", 1, 6, "⚔️"),
    createUnit("celt_warrior_2", "Celts", "Celtic Warrior", "Celtic Warrior", 2, 5, "⚔️"),
    createUnit("celt_warrior_3", "Celts", "Celtic Warrior", "Celtic Warrior", 5, 5, "⚔️"),
    createUnit("celt_warrior_4", "Celts", "Celtic Warrior", "Celtic Warrior", 6, 6, "⚔️"),
    createUnit("celt_archer_1", "Celts", "Celtic Archer", "Celtic Archer", 2, 7, "🏹"),
    createUnit("celt_archer_2", "Celts", "Celtic Archer", "Celtic Archer", 5, 7, "🏹"),
    createUnit("celt_cavalry", "Celts", "Celtic Cavalry", "Celtic Cavalry", 3, 5, "🐎")
  ],
  Level3: [
    createUnit("carthage_general", "Carthage", "Carthaginian General", "Carthaginian General", 2, 0, "👑"),
    createUnit("sacred_band", "Carthage", "Sacred Band", "Sacred Band", 3, 1, "🛡️"),
    createUnit("libyan_1", "Carthage", "Libyan Infantry", "Libyan Infantry", 2, 2, "⚔️"),
    createUnit("libyan_2", "Carthage", "Libyan Infantry", "Libyan Infantry", 3, 2, "⚔️"),
    createUnit("libyan_3", "Carthage", "Libyan Infantry", "Libyan Infantry", 4, 2, "⚔️"),
    createUnit("numidian", "Carthage", "Numidian Cavalry", "Numidian Cavalry", 6, 1, "🐎"),
    createUnit("slinger", "Carthage", "Balearic Slinger", "Balearic Slinger", 1, 3, "🏹"),
    createUnit("elephant", "Carthage", "War Elephant", "War Elephant", 5, 2, "🐘"),
    createUnit("jarl", "Vikings", "Jarl", "Jarl", 5, 7, "👑"),
    createUnit("shieldmaiden_1", "Vikings", "Shieldmaiden", "Shieldmaiden", 4, 6, "🛡️"),
    createUnit("shieldmaiden_2", "Vikings", "Shieldmaiden", "Shieldmaiden", 5, 6, "🛡️"),
    createUnit("raider_1", "Vikings", "Viking Raider", "Viking Raider", 3, 5, "🪓"),
    createUnit("raider_2", "Vikings", "Viking Raider", "Viking Raider", 5, 4, "🪓"),
    createUnit("raider_3", "Vikings", "Viking Raider", "Viking Raider", 6, 5, "🪓"),
    createUnit("viking_archer", "Vikings", "Viking Archer", "Viking Archer", 2, 5, "🏹"),
    createUnit("viking_scout", "Vikings", "Scout", "Scout", 6, 4, "🐎")
  ],
  Level4: [
    createUnit("germanic_king", "Germanic", "Germanic King", "Germanic King", 3, 0, "👑"),
    createUnit("germanic_warrior_1", "Germanic", "Germanic Warrior", "Germanic Warrior", 1, 1, "🪓"),
    createUnit("germanic_warrior_2", "Germanic", "Germanic Warrior", "Germanic Warrior", 5, 1, "🪓"),
    createUnit("germanic_warrior_3", "Germanic", "Germanic Warrior", "Germanic Warrior", 2, 2, "🪓"),
    createUnit("germanic_warrior_4", "Germanic", "Germanic Warrior", "Germanic Warrior", 4, 2, "🪓"),
    createUnit("germanic_archer_1", "Germanic", "Germanic Archer", "Germanic Archer", 0, 2, "🏹"),
    createUnit("germanic_archer_2", "Germanic", "Germanic Archer", "Germanic Archer", 6, 2, "🏹"),
    createUnit("wolf_rider", "Germanic", "Germanic Wolf Rider", "Germanic Wolf Rider", 3, 3, "🐎"),
    createUnit("teuton_king", "Teutons", "King", "King", 4, 7, "👑"),
    createUnit("manarms_1", "Teutons", "Man-at-Arms", "Man-at-Arms", 2, 6, "⚔️"),
    createUnit("manarms_2", "Teutons", "Man-at-Arms", "Man-at-Arms", 3, 6, "⚔️"),
    createUnit("manarms_3", "Teutons", "Man-at-Arms", "Man-at-Arms", 4, 6, "⚔️"),
    createUnit("manarms_4", "Teutons", "Man-at-Arms", "Man-at-Arms", 5, 6, "⚔️"),
    createUnit("longbow_1", "Teutons", "Longbowman", "Longbowman", 1, 5, "🏹"),
    createUnit("longbow_2", "Teutons", "Longbowman", "Longbowman", 6, 5, "🏹"),
    createUnit("knight", "Teutons", "Knight", "Knight", 4, 4, "🐎")
  ],
  Level5: [
    createUnit("roman_legionary_a", "Romans", "Legionary", "Legionary", 0, 1, "⚔️"),
    createUnit("roman_legionary_b", "Romans", "Legionary", "Legionary", 2, 0, "⚔️"),
    createUnit("roman_legionary_c", "Romans", "Legionary", "Legionary", 4, 1, "⚔️"),
    createUnit("roman_centurion", "Romans", "Centurion", "Centurion", 1, 2, "🪖"),
    createUnit("roman_legionary_d", "Romans", "Legionary", "Legionary", 3, 2, "⚔️"),
    createUnit("roman_archer_a", "Romans", "Archer", "Archer", 5, 0, "🏹"),
    createUnit("roman_archer_b", "Romans", "Archer", "Archer", 6, 1, "🏹"),
    createUnit("roman_archer_c", "Romans", "Archer", "Archer", 7, 2, "🏹"),
    createUnit("roman_cavalry_a", "Romans", "Cavalry", "Cavalry", 1, 3, "🐎"),
    createUnit("roman_cavalry_b", "Romans", "Cavalry", "Cavalry", 4, 3, "🐎"),
    createUnit("carthage_general_b", "Carthage", "Carthaginian General", "Carthaginian General", 6, 7, "👑"),
    createUnit("libyan_a", "Carthage", "Libyan Infantry", "Libyan Infantry", 2, 7, "⚔️"),
    createUnit("libyan_b", "Carthage", "Libyan Infantry", "Libyan Infantry", 4, 6, "⚔️"),
    createUnit("libyan_c", "Carthage", "Libyan Infantry", "Libyan Infantry", 6, 5, "⚔️"),
    createUnit("sacred_band_b", "Carthage", "Sacred Band", "Sacred Band", 5, 6, "🛡️"),
    createUnit("archer_carthage_a", "Carthage", "Carthaginian Archer", "Carthaginian Archer", 0, 6, "🏹"),
    createUnit("archer_carthage_b", "Carthage", "Carthaginian Archer", "Carthaginian Archer", 1, 5, "🏹"),
    createUnit("slinger_b", "Carthage", "Balearic Slinger", "Balearic Slinger", 3, 5, "🏹"),
    createUnit("numidian_a", "Carthage", "Numidian Cavalry", "Numidian Cavalry", 5, 4, "🐎"),
    createUnit("elephant_b", "Carthage", "War Elephant", "War Elephant", 7, 4, "🐘")
  ],
  Level6: [
    createUnit("greek_king_delta", "Greeks", "Macedonian King", "Macedonian King", 3, 0, "👑"),
    createUnit("hoplite_1", "Greeks", "Hoplite", "Hoplite", 2, 1, "⚔️"),
    createUnit("hoplite_2", "Greeks", "Hoplite", "Hoplite", 3, 1, "⚔️"),
    createUnit("hoplite_3", "Greeks", "Hoplite", "Hoplite", 4, 1, "⚔️"),
    createUnit("hoplite_4", "Greeks", "Hoplite", "Hoplite", 3, 2, "⚔️"),
    createUnit("greek_archer_delta_1", "Greeks", "Cretan Archer", "Cretan Archer", 1, 1, "🏹"),
    createUnit("greek_archer_delta_2", "Greeks", "Cretan Archer", "Cretan Archer", 5, 1, "🏹"),
    createUnit("greek_cavalry_delta", "Greeks", "Thessalian Cavalry", "Thessalian Cavalry", 6, 3, "🐎"),
    createUnit("germanic_king_delta", "Germanic", "Germanic King", "Germanic King", 4, 7, "👑"),
    createUnit("germanic_warrior_a", "Germanic", "Germanic Warrior", "Germanic Warrior", 2, 6, "🪓"),
    createUnit("germanic_warrior_b", "Germanic", "Germanic Warrior", "Germanic Warrior", 4, 6, "🪓"),
    createUnit("germanic_warrior_c", "Germanic", "Germanic Warrior", "Germanic Warrior", 6, 6, "🪓"),
    createUnit("germanic_warrior_d", "Germanic", "Germanic Warrior", "Germanic Warrior", 3, 5, "🪓"),
    createUnit("germanic_archer_a", "Germanic", "Germanic Archer", "Germanic Archer", 1, 5, "🏹"),
    createUnit("germanic_archer_b", "Germanic", "Germanic Archer", "Germanic Archer", 5, 5, "🏹"),
    createUnit("wolf_rider_delta", "Germanic", "Germanic Wolf Rider", "Germanic Wolf Rider", 0, 6, "🐎")
  ],
  Level7: [
    createUnit("celt_king_tercio", "Celts", "Celtic King", "Celtic King", 2, 0, "👑"),
    createUnit("celt_spear_1", "Celts", "Celtic Spearman", "Celtic Spearman", 1, 1, "⚔️"),
    createUnit("celt_spear_2", "Celts", "Celtic Spearman", "Celtic Spearman", 3, 1, "⚔️"),
    createUnit("celt_warrior_t1", "Celts", "Celtic Warrior", "Celtic Warrior", 0, 2, "⚔️"),
    createUnit("celt_warrior_t2", "Celts", "Celtic Warrior", "Celtic Warrior", 2, 2, "⚔️"),
    createUnit("celt_warrior_t3", "Celts", "Celtic Warrior", "Celtic Warrior", 4, 2, "⚔️"),
    createUnit("celt_archer_t", "Celts", "Celtic Archer", "Celtic Archer", 1, 3, "🏹"),
    createUnit("celt_cavalry_t", "Celts", "Celtic Cavalry", "Celtic Cavalry", 5, 2, "🐎"),
    createUnit("jarl_tercio", "Vikings", "Jarl", "Jarl", 5, 7, "👑"),
    createUnit("raider_t1", "Vikings", "Viking Raider", "Viking Raider", 3, 6, "🪓"),
    createUnit("raider_t2", "Vikings", "Viking Raider", "Viking Raider", 5, 6, "🪓"),
    createUnit("raider_t3", "Vikings", "Viking Raider", "Viking Raider", 2, 5, "🪓"),
    createUnit("raider_t4", "Vikings", "Viking Raider", "Viking Raider", 4, 5, "🪓"),
    createUnit("raider_t5", "Vikings", "Viking Raider", "Viking Raider", 6, 5, "🪓"),
    createUnit("viking_archer_t", "Vikings", "Viking Archer", "Viking Archer", 3, 4, "🏹"),
    createUnit("viking_scout_t", "Vikings", "Scout", "Scout", 6, 4, "🐎")
  ],
  Level8: [
    createUnit("barbarian_king_p", "Barbarians", "Barbarian Chief", "Barbarian Chief", 3, 0, "👑"),
    createUnit("barbarian_w1_p", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 0, 1, "🪓"),
    createUnit("barbarian_w2_p", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 1, 2, "🪓"),
    createUnit("barbarian_w3_p", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 5, 2, "🪓"),
    createUnit("barbarian_w4_p", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 6, 1, "🪓"),
    createUnit("barbarian_archer_p1", "Barbarians", "Barbarian Archer", "Barbarian Archer", 2, 1, "🏹"),
    createUnit("barbarian_archer_p2", "Barbarians", "Barbarian Archer", "Barbarian Archer", 4, 1, "🏹"),
    createUnit("barbarian_scout_p", "Barbarians", "Barbarian Scout", "Barbarian Scout", 7, 3, "🐎"),
    createUnit("teuton_king_p", "Teutons", "King", "King", 4, 7, "👑"),
    createUnit("teuton_spear_1", "Teutons", "Spearman", "Spearman", 2, 6, "⚔️"),
    createUnit("teuton_spear_2", "Teutons", "Spearman", "Spearman", 3, 6, "⚔️"),
    createUnit("teuton_arms_1", "Teutons", "Man-at-Arms", "Man-at-Arms", 4, 6, "⚔️"),
    createUnit("teuton_arms_2", "Teutons", "Man-at-Arms", "Man-at-Arms", 5, 6, "⚔️"),
    createUnit("teuton_longbow_1", "Teutons", "Longbowman", "Longbowman", 1, 5, "🏹"),
    createUnit("teuton_longbow_2", "Teutons", "Longbowman", "Longbowman", 6, 5, "🏹"),
    createUnit("teuton_trebuchet", "Teutons", "Trebuchet", "Trebuchet", 4, 4, "⚔️")
  ]
};