import { generateTroopStats } from "./troopStats";

const createUnit = (
  id: string,
  team: string,
  name: string,
  role: string,
  x: number,
  y: number,
  Icon: string
) => ({
  id,
  team,
  name,
  ...generateTroopStats(role),
  x,
  y,
  role,
  Icon
});

export const levels = {
  Level1: [
    createUnit("roman_king", "Romans", "Roman King", "Roman King", 3, 0, "👑"),
    createUnit("roman_ballista_left", "Romans", "Ballista", "Ballista", 0, 0, "⚔️"),
    createUnit("roman_ballista_right", "Romans", "Ballista", "Ballista", 7, 0, "⚔️"),
    createUnit("roman_praetorian", "Romans", "Praetorian", "Praetorian", 4, 0, "🪖"),
    createUnit("roman_cavalry_left", "Romans", "Cavalry", "Cavalry", 1, 1, "🐎"),
    createUnit("roman_archer_left", "Romans", "Archer", "Archer", 2, 1, "🏹"),
    createUnit("roman_archer_right", "Romans", "Archer", "Archer", 5, 1, "🏹"),
    createUnit("roman_cavalry_right", "Romans", "Cavalry", "Cavalry", 6, 1, "🐎"),
    createUnit("roman_legionary_1", "Romans", "Legionary", "Legionary", 0, 2, "⚔️"),
    createUnit("roman_legionary_2", "Romans", "Legionary", "Legionary", 1, 2, "⚔️"),
    createUnit("roman_legionary_3", "Romans", "Legionary", "Legionary", 2, 2, "⚔️"),
    createUnit("roman_legionary_4", "Romans", "Legionary", "Legionary", 3, 2, "⚔️"),
    createUnit("roman_legionary_5", "Romans", "Legionary", "Legionary", 4, 2, "⚔️"),
    createUnit("roman_legionary_6", "Romans", "Legionary", "Legionary", 5, 2, "⚔️"),
    createUnit("roman_legionary_7", "Romans", "Legionary", "Legionary", 6, 2, "⚔️"),
    createUnit("roman_legionary_8", "Romans", "Legionary", "Legionary", 7, 2, "⚔️"),
    createUnit("barbarian_chief", "Barbarians", "Barbarian Chief", "Barbarian Chief", 4, 7, "👑"),
    createUnit("barbarian_axeman_left", "Barbarians", "Barbarian Axeman", "Barbarian Axeman", 0, 7, "⚔️"),
    createUnit("barbarian_berserker", "Barbarians", "Barbarian Berserker", "Barbarian Berserker", 3, 7, "⚔️"),
    createUnit("barbarian_axeman_right", "Barbarians", "Barbarian Axeman", "Barbarian Axeman", 7, 7, "⚔️"),
    createUnit("barbarian_scout_left", "Barbarians", "Barbarian Scout", "Barbarian Scout", 1, 6, "🐎🏹"),
    createUnit("barbarian_archer_left", "Barbarians", "Barbarian Archer", "Barbarian Archer", 2, 6, "🏹"),
    createUnit("barbarian_archer_right", "Barbarians", "Barbarian Archer", "Barbarian Archer", 5, 6, "🏹"),
    createUnit("barbarian_scout_right", "Barbarians", "Barbarian Scout", "Barbarian Scout", 6, 6, "🐎🏹"),
    createUnit("barbarian_warrior_1", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 0, 5, "🪓"),
    createUnit("barbarian_warrior_2", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 1, 5, "🪓"),
    createUnit("barbarian_warrior_3", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 2, 5, "🪓"),
    createUnit("barbarian_warrior_4", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 3, 5, "🪓"),
    createUnit("barbarian_warrior_5", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 4, 5, "🪓"),
    createUnit("barbarian_warrior_6", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 5, 5, "🪓"),
    createUnit("barbarian_warrior_7", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 6, 5, "🪓"),
    createUnit("barbarian_warrior_8", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 7, 5, "🪓")
  ],
  Level2: [
    createUnit("greek_king", "Greeks", "Macedonian King", "Macedonian King", 3, 0, "👑"),
    createUnit("greek_hoplite_1", "Greeks", "Hoplite", "Hoplite", 2, 1, "⚔️"),
    createUnit("greek_hoplite_2", "Greeks", "Hoplite", "Hoplite", 3, 1, "⚔️"),
    createUnit("greek_hoplite_3", "Greeks", "Hoplite", "Hoplite", 4, 1, "⚔️"),
    createUnit("greek_hoplite_4", "Greeks", "Hoplite", "Hoplite", 3, 2, "⚔️"),
    createUnit("greek_archer_1", "Greeks", "Cretan Archer", "Cretan Archer", 1, 2, "🏹"),
    createUnit("greek_archer_2", "Greeks", "Cretan Archer", "Cretan Archer", 5, 2, "🏹"),
    createUnit("greek_cavalry", "Greeks", "Companion Cavalry", "Companion Cavalry", 6, 1, "🐎"),
    createUnit("celt_king", "Gauls", "Gallic King", "Gallic King", 4, 7, "👑"),
    createUnit("celt_warrior_1", "Gauls", "Gallic Warrior", "Gallic Warrior", 1, 6, "⚔️"),
    createUnit("celt_warrior_2", "Gauls", "Gallic Warrior", "Gallic Warrior", 2, 5, "⚔️"),
    createUnit("celt_warrior_3", "Gauls", "Gallic Warrior", "Gallic Warrior", 5, 5, "⚔️"),
    createUnit("celt_warrior_4", "Gauls", "Gallic Warrior", "Gallic Warrior", 6, 6, "⚔️"),
    createUnit("celt_archer_1", "Gauls", "Gallic Archer", "Gallic Archer", 2, 7, "🏹"),
    createUnit("celt_archer_2", "Gauls", "Gallic Archer", "Gallic Archer", 5, 7, "🏹"),
    createUnit("celt_cavalry", "Gauls", "Gallic Cavalry", "Gallic Cavalry", 3, 5, "🐎")
  ],
  Level3: [
    createUnit("carthage_general", "Carthage", "Carthaginian General", "Carthaginian General", 2, 0, "👑"),
    createUnit("sacred_band", "Carthage", "Sacred Band", "Sacred Band", 3, 1, "🛡️"),
    createUnit("libyan_1", "Carthage", "Libyan Infantry", "Libyan Infantry", 2, 2, "⚔️"),
    createUnit("libyan_2", "Carthage", "Libyan Infantry", "Libyan Infantry", 3, 2, "⚔️"),
    createUnit("libyan_3", "Carthage", "Libyan Infantry", "Libyan Infantry", 4, 2, "⚔️"),
    createUnit("numidian", "Carthage", "Numidian Cavalry", "Numidian Cavalry", 6, 1, "🐎"),
    createUnit("slinger", "Carthage", "Balearic Slinger", "Balearic Slinger", 1, 3, "🏹"),
    createUnit("elephant", "Carthage", "War Elephant", "War Elephant", 5, 2, "🐘"),
    createUnit("jarl", "Vikings", "Viking Jarl", "Jarl", 5, 7, "👑"),
    createUnit("shieldmaiden_1", "Vikings", "Shieldmaiden", "Shieldmaiden", 4, 6, "🛡️"),
    createUnit("shieldmaiden_2", "Vikings", "Shieldmaiden", "Shieldmaiden", 5, 6, "🛡️"),
    createUnit("raider_1", "Vikings", "Viking Raider", "Viking Raider", 3, 5, "🪓"),
    createUnit("raider_2", "Vikings", "Viking Raider", "Viking Raider", 5, 4, "🪓"),
    createUnit("raider_3", "Vikings", "Viking Raider", "Viking Raider", 6, 5, "🪓"),
    createUnit("viking_archer", "Vikings", "Viking Archer", "Viking Archer", 2, 5, "🏹"),
    createUnit("viking_scout", "Vikings", "Scout", "Scout", 6, 4, "🐎🏹")
  ],
  Level4: [
    createUnit("germanic_king", "Germanic", "Germanic King", "Germanic King", 3, 0, "👑"),
    createUnit("germanic_warrior_1", "Germanic", "Germanic Warrior", "Germanic Warrior", 1, 1, "🪓"),
    createUnit("germanic_warrior_2", "Germanic", "Germanic Warrior", "Germanic Warrior", 5, 1, "🪓"),
    createUnit("germanic_warrior_3", "Germanic", "Germanic Warrior", "Germanic Warrior", 2, 2, "🪓"),
    createUnit("germanic_warrior_4", "Germanic", "Germanic Warrior", "Germanic Warrior", 4, 2, "🪓"),
    createUnit("germanic_archer_1", "Germanic", "Germanic Archer", "Germanic Archer", 0, 2, "🏹"),
    createUnit("germanic_archer_2", "Germanic", "Germanic Archer", "Germanic Archer", 6, 2, "🏹"),
    createUnit("wolf_rider", "Germanic", "Germanic Wolf Rider", "Germanic Wolf Rider", 3, 3, "🐎"),
    createUnit("egypt_pharaoh_l4", "Egypt", "Pharaoh", "Pharaoh", 4, 7, "👑"),
    createUnit("egypt_guard_l4a", "Egypt", "Royal Guard", "Royal Guard", 2, 6, "⚔️"),
    createUnit("egypt_guard_l4b", "Egypt", "Royal Guard", "Royal Guard", 5, 6, "⚔️"),
    createUnit("egypt_medjay_l4", "Egypt", "Medjay", "Medjay", 3, 6, "⚔️"),
    createUnit("egypt_warrior_l4", "Egypt", "Egyptian Warrior", "Egyptian Warrior", 4, 6, "⚔️"),
    createUnit("egypt_archer_l4", "Egypt", "Egyptian Archer", "Egyptian Archer", 1, 5, "🏹"),
    createUnit("egypt_archer_l4b", "Egypt", "Nubian Archer", "Nubian Archer", 6, 5, "🏹"),
    createUnit("egypt_chariot_l4", "Egypt", "War Chariot", "War Chariot", 4, 4, "🐎")
  ],
  Level5: [
    createUnit("roman_legionary_a", "Romans", "Legionary", "Legionary", 0, 1, "⚔️"),
    createUnit("roman_legionary_b", "Romans", "Legionary", "Legionary", 2, 0, "⚔️"),
    createUnit("roman_legionary_c", "Romans", "Legionary", "Legionary", 4, 1, "⚔️"),
    createUnit("roman_centurion", "Romans", "Centurion", "Centurion", 1, 2, "🪖"),
    createUnit("roman_legionary_d", "Romans", "Legionary", "Legionary", 3, 2, "⚔️"),
    createUnit("roman_archer_a", "Romans", "Archer", "Archer", 5, 0, "🏹"),
    createUnit("roman_archer_b", "Romans", "Archer", "Archer", 6, 1, "🏹"),
    createUnit("roman_archer_c", "Romans", "Archer", "Archer", 7, 2, "🏹"),
    createUnit("roman_cavalry_a", "Romans", "Cavalry", "Cavalry", 1, 3, "🐎"),
    createUnit("roman_cavalry_b", "Romans", "Cavalry", "Cavalry", 4, 3, "🐎"),
    createUnit("carthage_general_b", "Carthage", "Carthaginian General", "Carthaginian General", 6, 7, "👑"),
    createUnit("libyan_a", "Carthage", "Libyan Infantry", "Libyan Infantry", 2, 7, "⚔️"),
    createUnit("libyan_b", "Carthage", "Libyan Infantry", "Libyan Infantry", 4, 6, "⚔️"),
    createUnit("libyan_c", "Carthage", "Libyan Infantry", "Libyan Infantry", 6, 5, "⚔️"),
    createUnit("sacred_band_b", "Carthage", "Sacred Band", "Sacred Band", 5, 6, "🛡️"),
    createUnit("archer_carthage_a", "Carthage", "Carthaginian Archer", "Carthaginian Archer", 0, 6, "🏹"),
    createUnit("archer_carthage_b", "Carthage", "Carthaginian Archer", "Carthaginian Archer", 1, 5, "🏹"),
    createUnit("slinger_b", "Carthage", "Balearic Slinger", "Balearic Slinger", 3, 5, "🏹"),
    createUnit("numidian_a", "Carthage", "Numidian Cavalry", "Numidian Cavalry", 5, 4, "🐎"),
    createUnit("elephant_b", "Carthage", "War Elephant", "War Elephant", 7, 4, "🐘")
  ],
  Level6: [
    createUnit("greek_king_delta", "Greeks", "Macedonian King", "Macedonian King", 3, 0, "👑"),
    createUnit("hoplite_1", "Greeks", "Hoplite", "Hoplite", 2, 1, "⚔️"),
    createUnit("hoplite_2", "Greeks", "Hoplite", "Hoplite", 3, 1, "⚔️"),
    createUnit("hoplite_3", "Greeks", "Hoplite", "Hoplite", 4, 1, "⚔️"),
    createUnit("hoplite_4", "Greeks", "Hoplite", "Hoplite", 3, 2, "⚔️"),
    createUnit("greek_archer_delta_1", "Greeks", "Cretan Archer", "Cretan Archer", 1, 1, "🏹"),
    createUnit("greek_archer_delta_2", "Greeks", "Cretan Archer", "Cretan Archer", 5, 1, "🏹"),
    createUnit("greek_cavalry_delta", "Greeks", "Thessalian Cavalry", "Thessalian Cavalry", 6, 3, "🐎"),
    createUnit("germanic_king_delta", "Germanic", "Germanic King", "Germanic King", 4, 7, "👑"),
    createUnit("germanic_warrior_a", "Germanic", "Germanic Warrior", "Germanic Warrior", 2, 6, "🪓"),
    createUnit("germanic_warrior_b", "Germanic", "Germanic Warrior", "Germanic Warrior", 4, 6, "🪓"),
    createUnit("germanic_warrior_c", "Germanic", "Germanic Warrior", "Germanic Warrior", 6, 6, "🪓"),
    createUnit("germanic_warrior_d", "Germanic", "Germanic Warrior", "Germanic Warrior", 3, 5, "🪓"),
    createUnit("germanic_archer_a", "Germanic", "Germanic Archer", "Germanic Archer", 1, 5, "🏹"),
    createUnit("germanic_archer_b", "Germanic", "Germanic Archer", "Germanic Archer", 5, 5, "🏹"),
    createUnit("wolf_rider_delta", "Germanic", "Germanic Wolf Rider", "Germanic Wolf Rider", 0, 6, "🐎")
  ],
  Level7: [
    createUnit("celt_king_tercio", "Gauls", "Gallic King", "Gallic King", 2, 0, "👑"),
    createUnit("celt_spear_1", "Gauls", "Gallic Spearman", "Gallic Spearman", 1, 1, "⚔️"),
    createUnit("celt_spear_2", "Gauls", "Gallic Spearman", "Gallic Spearman", 3, 1, "⚔️"),
    createUnit("celt_warrior_t1", "Gauls", "Gallic Warrior", "Gallic Warrior", 0, 2, "⚔️"),
    createUnit("celt_warrior_t2", "Gauls", "Gallic Warrior", "Gallic Warrior", 2, 2, "⚔️"),
    createUnit("celt_warrior_t3", "Gauls", "Gallic Warrior", "Gallic Warrior", 4, 2, "⚔️"),
    createUnit("celt_archer_t", "Gauls", "Gallic Archer", "Gallic Archer", 1, 3, "🏹"),
    createUnit("celt_cavalry_t", "Gauls", "Gallic Cavalry", "Gallic Cavalry", 5, 2, "🐎"),
    createUnit("jarl_tercio", "Vikings", "Viking Jarl", "Jarl", 5, 7, "👑"),
    createUnit("raider_t1", "Vikings", "Viking Raider", "Viking Raider", 3, 6, "🪓"),
    createUnit("raider_t2", "Vikings", "Viking Raider", "Viking Raider", 5, 6, "🪓"),
    createUnit("raider_t3", "Vikings", "Viking Raider", "Viking Raider", 2, 5, "🪓"),
    createUnit("raider_t4", "Vikings", "Viking Raider", "Viking Raider", 4, 5, "🪓"),
    createUnit("raider_t5", "Vikings", "Viking Raider", "Viking Raider", 6, 5, "🪓"),
    createUnit("viking_archer_t", "Vikings", "Viking Archer", "Viking Archer", 3, 4, "🏹"),
    createUnit("viking_scout_t", "Vikings", "Scout", "Scout", 6, 4, "🐎🏹")
  ],
  Level8: [
    createUnit("barbarian_king_p", "Barbarians", "Barbarian Chief", "Barbarian Chief", 3, 0, "👑"),
    createUnit("barbarian_w1_p", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 0, 1, "🪓"),
    createUnit("barbarian_w2_p", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 1, 2, "🪓"),
    createUnit("barbarian_w3_p", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 5, 2, "🪓"),
    createUnit("barbarian_w4_p", "Barbarians", "Barbarian Warrior", "Barbarian Warrior", 6, 1, "🪓"),
    createUnit("barbarian_archer_p1", "Barbarians", "Barbarian Archer", "Barbarian Archer", 2, 1, "🏹"),
    createUnit("barbarian_archer_p2", "Barbarians", "Barbarian Archer", "Barbarian Archer", 4, 1, "🏹"),
    createUnit("barbarian_scout_p", "Barbarians", "Barbarian Scout", "Barbarian Scout", 7, 3, "🐎🏹"),
    createUnit("egypt_pharaoh_l8", "Egypt", "Pharaoh", "Pharaoh", 4, 7, "👑"),
    createUnit("egypt_shield_l8a", "Egypt", "Shield Bearer", "Shield Bearer", 2, 6, "⚔️"),
    createUnit("egypt_shield_l8b", "Egypt", "Shield Bearer", "Shield Bearer", 5, 6, "⚔️"),
    createUnit("egypt_warrior_l8a", "Egypt", "Egyptian Warrior", "Egyptian Warrior", 3, 6, "⚔️"),
    createUnit("egypt_warrior_l8b", "Egypt", "Egyptian Warrior", "Egyptian Warrior", 4, 6, "⚔️"),
    createUnit("egypt_archer_l8", "Egypt", "Egyptian Archer", "Egyptian Archer", 1, 5, "🏹"),
    createUnit("egypt_archer_l8b", "Egypt", "Nubian Archer", "Nubian Archer", 6, 5, "🏹"),
    createUnit("egypt_catapult_l8", "Egypt", "Egyptian Catapult", "Egyptian Catapult", 4, 4, "⚙️")
  ],
  Level9: [
    createUnit("egypt_pharaoh_1", "Egypt", "Pharaoh", "Pharaoh", 3, 0, "👑"),
    createUnit("egypt_guard_1", "Egypt", "Royal Guard", "Royal Guard", 2, 1, "⚔️"),
    createUnit("egypt_guard_2", "Egypt", "Royal Guard", "Royal Guard", 4, 1, "⚔️"),
    createUnit("egypt_khopesh_1", "Egypt", "Khopesh Warrior", "Khopesh Warrior", 1, 2, "⚔️"),
    createUnit("egypt_medjay_1", "Egypt", "Medjay", "Medjay", 3, 2, "⚔️"),
    createUnit("egypt_shield_1", "Egypt", "Shield Bearer", "Shield Bearer", 5, 2, "⚔️"),
    createUnit("egypt_archer_1", "Egypt", "Egyptian Archer", "Egyptian Archer", 2, 3, "🏹"),
    createUnit("egypt_archer_2", "Egypt", "Nubian Archer", "Nubian Archer", 4, 3, "🏹"),
    createUnit("egypt_chariot_1", "Egypt", "War Chariot", "War Chariot", 0, 3, "🐎"),
    createUnit("egypt_scout_1", "Egypt", "Desert Scout", "Desert Scout", 7, 3, "🐎🏹"),
    createUnit("roman_king_9", "Romans", "Roman King", "Roman King", 4, 7, "👑"),
    createUnit("roman_praetorian_9", "Romans", "Praetorian", "Praetorian", 3, 6, "🪖"),
    createUnit("roman_centurion_9", "Romans", "Centurion", "Centurion", 5, 6, "🪖"),
    createUnit("roman_legionary_9a", "Romans", "Legionary", "Legionary", 2, 5, "⚔️"),
    createUnit("roman_legionary_9b", "Romans", "Legionary", "Legionary", 4, 5, "⚔️"),
    createUnit("roman_legionary_9c", "Romans", "Legionary", "Legionary", 6, 5, "⚔️"),
    createUnit("roman_archer_9", "Romans", "Archer", "Archer", 1, 4, "🏹"),
    createUnit("roman_ballista_9", "Romans", "Ballista", "Ballista", 4, 4, "⚙️"),
    createUnit("roman_cavalry_9a", "Romans", "Cavalry", "Cavalry", 0, 4, "🐎"),
    createUnit("roman_cavalry_9b", "Romans", "Cavalry", "Cavalry", 7, 4, "🐎")
  ],
  Level10: [
    createUnit("egypt_pharaoh_2", "Egypt", "Pharaoh", "Pharaoh", 3, 0, "👑"),
    createUnit("egypt_warrior_10a", "Egypt", "Egyptian Warrior", "Egyptian Warrior", 2, 1, "⚔️"),
    createUnit("egypt_warrior_10b", "Egypt", "Egyptian Warrior", "Egyptian Warrior", 4, 1, "⚔️"),
    createUnit("egypt_guard_10", "Egypt", "Royal Guard", "Royal Guard", 3, 2, "⚔️"),
    createUnit("egypt_archer_10a", "Egypt", "Egyptian Archer", "Egyptian Archer", 1, 2, "🏹"),
    createUnit("egypt_archer_10b", "Egypt", "Nubian Archer", "Nubian Archer", 5, 2, "🏹"),
    createUnit("egypt_chariot_10", "Egypt", "Royal Chariot", "Royal Chariot", 6, 3, "🐎🏹"),
    createUnit("egypt_catapult_10", "Egypt", "Egyptian Catapult", "Egyptian Catapult", 0, 3, "⚙️"),
    createUnit("greek_king_10", "Greeks", "Macedonian King", "Macedonian King", 4, 7, "👑"),
    createUnit("greek_hoplite_10a", "Greeks", "Hoplite", "Hoplite", 2, 6, "⚔️"),
    createUnit("greek_hoplite_10b", "Greeks", "Hoplite", "Hoplite", 3, 6, "⚔️"),
    createUnit("greek_hoplite_10c", "Greeks", "Hoplite", "Hoplite", 4, 6, "⚔️"),
    createUnit("greek_hoplite_10d", "Greeks", "Hoplite", "Hoplite", 5, 6, "⚔️"),
    createUnit("greek_archer_10a", "Greeks", "Cretan Archer", "Cretan Archer", 1, 5, "🏹"),
    createUnit("greek_archer_10b", "Greeks", "Cretan Archer", "Cretan Archer", 6, 5, "🏹"),
    createUnit("greek_cavalry_10a", "Greeks", "Companion Cavalry", "Companion Cavalry", 0, 5, "🐎"),
    createUnit("greek_cavalry_10b", "Greeks", "Thessalian Cavalry", "Thessalian Cavalry", 7, 5, "🐎")
  ],
  Level11: [
    createUnit("gaul_king_11", "Gauls", "Gallic King", "Gallic King", 3, 0, "👑"),
    createUnit("gaul_warrior_11a", "Gauls", "Gallic Warrior", "Gallic Warrior", 2, 1, "⚔️"),
    createUnit("gaul_warrior_11b", "Gauls", "Gallic Warrior", "Gallic Warrior", 4, 1, "⚔️"),
    createUnit("gaul_spear_11a", "Gauls", "Gallic Spearman", "Gallic Spearman", 1, 2, "⚔️"),
    createUnit("gaul_spear_11b", "Gauls", "Gallic Spearman", "Gallic Spearman", 5, 2, "⚔️"),
    createUnit("gaul_archer_11a", "Gauls", "Gallic Archer", "Gallic Archer", 2, 3, "🏹"),
    createUnit("gaul_archer_11b", "Gauls", "Gallic Archer", "Gallic Archer", 4, 3, "🏹"),
    createUnit("gaul_cavalry_11", "Gauls", "Gallic Cavalry", "Gallic Cavalry", 6, 2, "🐎"),
    createUnit("carthage_general_11", "Carthage", "Carthaginian General", "Carthaginian General", 4, 7, "👑"),
    createUnit("carthage_band_11", "Carthage", "Sacred Band", "Sacred Band", 3, 6, "🛡️"),
    createUnit("carthage_libyan_11a", "Carthage", "Libyan Infantry", "Libyan Infantry", 2, 5, "⚔️"),
    createUnit("carthage_libyan_11b", "Carthage", "Libyan Infantry", "Libyan Infantry", 4, 5, "⚔️"),
    createUnit("carthage_archer_11", "Carthage", "Carthaginian Archer", "Carthaginian Archer", 1, 5, "🏹"),
    createUnit("carthage_slinger_11", "Carthage", "Balearic Slinger", "Balearic Slinger", 5, 5, "🏹"),
    createUnit("carthage_numidian_11", "Carthage", "Numidian Cavalry", "Numidian Cavalry", 6, 4, "🐎"),
    createUnit("carthage_elephant_11", "Carthage", "War Elephant", "War Elephant", 3, 4, "🐘")
  ],
  Level12: [
    createUnit("viking_jarl_12", "Vikings", "Viking Jarl", "Jarl", 3, 0, "👑"),
    createUnit("viking_huscarl_12a", "Vikings", "Huscarl", "Huscarl", 2, 1, "⚔️"),
    createUnit("viking_huscarl_12b", "Vikings", "Huscarl", "Huscarl", 4, 1, "⚔️"),
    createUnit("viking_ulf_12", "Vikings", "Ulfhednar", "Ulfhednar", 1, 2, "⚔️"),
    createUnit("viking_raider_12a", "Vikings", "Viking Raider", "Viking Raider", 3, 2, "🪓"),
    createUnit("viking_raider_12b", "Vikings", "Viking Raider", "Viking Raider", 5, 2, "🪓"),
    createUnit("viking_archer_12", "Vikings", "Viking Archer", "Viking Archer", 2, 3, "🏹"),
    createUnit("viking_varangian_12", "Vikings", "Varangian Guard", "Varangian Guard", 6, 2, "⚔️"),
    createUnit("egypt_pharaoh_12", "Egypt", "Pharaoh", "Pharaoh", 4, 7, "👑"),
    createUnit("egypt_guard_12", "Egypt", "Royal Guard", "Royal Guard", 5, 6, "⚔️"),
    createUnit("egypt_medjay_12", "Egypt", "Medjay", "Medjay", 2, 6, "⚔️"),
    createUnit("egypt_khopesh_12", "Egypt", "Khopesh Warrior", "Khopesh Warrior", 3, 6, "⚔️"),
    createUnit("egypt_shield_12", "Egypt", "Shield Bearer", "Shield Bearer", 4, 6, "⚔️"),
    createUnit("egypt_archer_12", "Egypt", "Nubian Archer", "Nubian Archer", 1, 5, "🏹"),
    createUnit("egypt_chariot_12", "Egypt", "Royal Chariot", "Royal Chariot", 6, 5, "🐎🏹"),
    createUnit("egypt_catapult_12", "Egypt", "Egyptian Catapult", "Egyptian Catapult", 4, 4, "⚙️")
  ],
  Level13: [
    createUnit("thracian_king_13", "Thracians", "Thracian King", "Thracian King", 3, 0, "👑"),
    createUnit("thracian_guard_13", "Thracians", "Thracian Guard", "Thracian Guard", 3, 1, "🪖"),
    createUnit("thracian_warrior_13a", "Thracians", "Thracian Warrior", "Thracian Warrior", 2, 2, "⚔️"),
    createUnit("thracian_rhomphaia_13", "Thracians", "Rhomphaia Fighter", "Rhomphaia Fighter", 4, 2, "⚔️"),
    createUnit("thracian_falx_13", "Thracians", "Falx Warrior", "Falx Warrior", 1, 3, "⚔️"),
    createUnit("thracian_spear_13", "Thracians", "Thracian Spearman", "Thracian Spearman", 5, 3, "⚔️"),
    createUnit("thracian_peltast_13", "Thracians", "Thracian Peltast", "Thracian Peltast", 2, 1, "🏹"),
    createUnit("thracian_archer_13", "Thracians", "Thracian Archer", "Thracian Archer", 4, 1, "🏹"),
    createUnit("thracian_rider_13", "Thracians", "Thracian Rider", "Thracian Rider", 0, 2, "🐎"),
    createUnit("thracian_noble_13", "Thracians", "Thracian Noble Rider", "Thracian Noble Rider", 7, 2, "🐎"),
    createUnit("dacian_king_13", "Dacians", "Dacian King", "Dacian King", 4, 7, "👑"),
    createUnit("dacian_guard_13", "Dacians", "Dacian Guard", "Dacian Guard", 4, 6, "🪖"),
    createUnit("dacian_warrior_13a", "Dacians", "Dacian Warrior", "Dacian Warrior", 3, 5, "⚔️"),
    createUnit("dacian_falx_13", "Dacians", "Falxman", "Falxman", 5, 5, "⚔️"),
    createUnit("dacian_spear_13", "Dacians", "Dacian Spearman", "Dacian Spearman", 2, 4, "⚔️"),
    createUnit("dacian_shield_13", "Dacians", "Dacian Shield Bearer", "Dacian Shield Bearer", 6, 4, "🛡️"),
    createUnit("dacian_slinger_13", "Dacians", "Dacian Slinger", "Dacian Slinger", 3, 6, "🏹"),
    createUnit("dacian_archer_13", "Dacians", "Dacian Archer", "Dacian Archer", 5, 6, "🏹"),
    createUnit("dacian_rider_13", "Dacians", "Dacian Rider", "Dacian Rider", 1, 5, "🐎"),
    createUnit("dacian_noble_13", "Dacians", "Dacian Noble Rider", "Dacian Noble Rider", 7, 5, "🐎")
  ],
  Level14: [
    createUnit("parthian_king_14", "Parthians", "Parthian King", "Parthian King", 3, 0, "👑"),
    createUnit("parthian_cataphract_14", "Parthians", "Cataphract", "Parthian Cataphract", 1, 1, "🐎"),
    createUnit("parthian_noble_14", "Parthians", "Parthian Noble Rider", "Parthian Noble Rider", 6, 1, "🐎"),
    createUnit("parthian_warrior_14", "Parthians", "Parthian Warrior", "Parthian Warrior", 2, 2, "⚔️"),
    createUnit("parthian_spear_14", "Parthians", "Parthian Spearman", "Parthian Spearman", 4, 2, "⚔️"),
    createUnit("parthian_horse_archer_14a", "Parthians", "Horse Archer", "Horse Archer", 0, 3, "🏹🐎"),
    createUnit("parthian_horse_archer_14b", "Parthians", "Elite Horse Archer", "Elite Horse Archer", 7, 3, "🏹🐎"),
    createUnit("parthian_archer_14", "Parthians", "Parthian Archer", "Parthian Archer", 3, 1, "🏹"),
    createUnit("parthian_camel_14", "Parthians", "Camel Rider", "Camel Rider", 5, 3, "🐪"),
    createUnit("parthian_ballista_14", "Parthians", "Parthian Ballista", "Parthian Ballista", 3, 2, "⚙️"),
    createUnit("seleucid_king_14", "Seleucids", "Seleucid King", "Seleucid King", 4, 7, "👑"),
    createUnit("seleucid_silver_14", "Seleucids", "Silver Shield Infantry", "Silver Shield Infantry", 4, 6, "🪖"),
    createUnit("seleucid_phalanx_14a", "Seleucids", "Phalangite", "Seleucid Phalangite", 2, 5, "⚔️"),
    createUnit("seleucid_phalanx_14b", "Seleucids", "Phalangite", "Seleucid Phalangite", 5, 5, "⚔️"),
    createUnit("seleucid_thorakitai_14", "Seleucids", "Thorakitai", "Thorakitai", 3, 5, "⚔️"),
    createUnit("seleucid_archer_14", "Seleucids", "Eastern Archer", "Eastern Archer", 2, 6, "🏹"),
    createUnit("seleucid_slinger_14", "Seleucids", "Slinger", "Seleucid Slinger", 6, 6, "🏹"),
    createUnit("seleucid_cavalry_14", "Seleucids", "Light Cavalry", "Seleucid Light Cavalry", 1, 4, "🐎"),
    createUnit("seleucid_elephant_14", "Seleucids", "War Elephant", "Seleucid War Elephant", 6, 4, "🐘"),
    createUnit("seleucid_catapult_14", "Seleucids", "Seleucid Catapult", "Seleucid Catapult", 4, 4, "⚙️")
  ],
  Level15: [
    createUnit("thracian_king_15", "Thracians", "Thracian King", "Thracian King", 2, 0, "👑"),
    createUnit("thracian_guard_15", "Thracians", "Thracian Guard", "Thracian Guard", 3, 1, "🪖"),
    createUnit("thracian_warrior_15", "Thracians", "Thracian Warrior", "Thracian Warrior", 2, 2, "⚔️"),
    createUnit("thracian_falx_15", "Thracians", "Falx Warrior", "Falx Warrior", 4, 2, "⚔️"),
    createUnit("thracian_spear_15", "Thracians", "Thracian Spearman", "Thracian Spearman", 1, 3, "⚔️"),
    createUnit("thracian_peltast_15", "Thracians", "Thracian Peltast", "Thracian Peltast", 0, 2, "🏹"),
    createUnit("thracian_archer_15", "Thracians", "Thracian Archer", "Thracian Archer", 5, 1, "🏹"),
    createUnit("thracian_drummer_15", "Thracians", "War Drummer", "War Drummer", 3, 2, "🥁"),
    createUnit("thracian_catapult_15", "Thracians", "Thracian Catapult", "Thracian Catapult", 7, 2, "⚙️"),
    createUnit("parthian_king_15", "Parthians", "Parthian King", "Parthian King", 5, 7, "👑"),
    createUnit("parthian_cataphract_15", "Parthians", "Cataphract", "Parthian Cataphract", 6, 6, "🐎"),
    createUnit("parthian_warrior_15", "Parthians", "Parthian Warrior", "Parthian Warrior", 4, 5, "⚔️"),
    createUnit("parthian_spear_15", "Parthians", "Parthian Spearman", "Parthian Spearman", 5, 5, "⚔️"),
    createUnit("parthian_archer_15", "Parthians", "Parthian Archer", "Parthian Archer", 6, 5, "🏹"),
    createUnit("parthian_horse_archer_15", "Parthians", "Horse Archer", "Horse Archer", 1, 6, "🏹🐎"),
    createUnit("parthian_elite_15", "Parthians", "Elite Horse Archer", "Elite Horse Archer", 7, 5, "🏹🐎"),
    createUnit("parthian_camel_15", "Parthians", "Camel Rider", "Camel Rider", 2, 5, "🐪"),
    createUnit("parthian_scout_15", "Parthians", "Scout Rider", "Scout Rider", 0, 5, "🐎"),
    createUnit("parthian_ballista_15", "Parthians", "Parthian Ballista", "Parthian Ballista", 3, 4, "⚙️")
  ],
  Level16: [
    createUnit("dacian_king_16", "Dacians", "Dacian King", "Dacian King", 3, 0, "👑"),
    createUnit("dacian_guard_16", "Dacians", "Dacian Guard", "Dacian Guard", 3, 1, "🪖"),
    createUnit("dacian_warrior_16a", "Dacians", "Dacian Warrior", "Dacian Warrior", 2, 2, "⚔️"),
    createUnit("dacian_warrior_16b", "Dacians", "Dacian Warrior", "Dacian Warrior", 4, 2, "⚔️"),
    createUnit("dacian_falx_16", "Dacians", "Falxman", "Falxman", 1, 3, "⚔️"),
    createUnit("dacian_shield_16", "Dacians", "Dacian Shield Bearer", "Dacian Shield Bearer", 5, 3, "🛡️"),
    createUnit("dacian_slinger_16", "Dacians", "Dacian Slinger", "Dacian Slinger", 2, 1, "🏹"),
    createUnit("dacian_archer_16", "Dacians", "Dacian Archer", "Dacian Archer", 4, 1, "🏹"),
    createUnit("dacian_catapult_16", "Dacians", "Dacian Catapult", "Dacian Catapult", 7, 2, "⚙️"),
    createUnit("seleucid_king_16", "Seleucids", "Seleucid King", "Seleucid King", 4, 7, "👑"),
    createUnit("seleucid_silver_16", "Seleucids", "Silver Shield Infantry", "Silver Shield Infantry", 4, 6, "🪖"),
    createUnit("seleucid_phalanx_16a", "Seleucids", "Phalangite", "Seleucid Phalangite", 2, 5, "⚔️"),
    createUnit("seleucid_phalanx_16b", "Seleucids", "Phalangite", "Seleucid Phalangite", 5, 5, "⚔️"),
    createUnit("seleucid_spear_16", "Seleucids", "Eastern Spearman", "Eastern Spearman", 3, 5, "⚔️"),
    createUnit("seleucid_archer_16", "Seleucids", "Eastern Archer", "Eastern Archer", 2, 6, "🏹"),
    createUnit("seleucid_slinger_16", "Seleucids", "Slinger", "Seleucid Slinger", 6, 6, "🏹"),
    createUnit("seleucid_cataphract_16", "Seleucids", "Cataphract", "Seleucid Cataphract", 1, 5, "🐎"),
    createUnit("seleucid_elephant_16", "Seleucids", "War Elephant", "Seleucid War Elephant", 6, 4, "🐘"),
    createUnit("seleucid_catapult_16", "Seleucids", "Seleucid Catapult", "Seleucid Catapult", 4, 4, "⚙️")
  ]
};